import { ArrowRight, Check, Globe2 } from "lucide-react";
import { Link } from "react-router-dom";
import { Eyebrow, PageIntro, PageShell, Testimonial } from "@/components/LuminorSite";

const team = [
  ["Elena Vance", "Founder + Creative Director", "https://images.unsplash.com/photo-1633381521050-26bb467d9d5a?auto=format&fit=crop&w=700&q=85"],
  ["Marcus Sterling", "Head of Growth", "https://images.unsplash.com/photo-1606143412458-acc5f86de897?auto=format&fit=crop&w=700&q=85"],
  ["Chloe Lin", "Head of Content Studio", "https://images.unsplash.com/photo-1629511565591-a1d494ad6c58?auto=format&fit=crop&w=700&q=85"],
];
const values = [["01", "Radical truth", "The best work starts with an honest read of where you are — and what the market is missing."], ["02", "Aesthetic supremacy", "We treat every touchpoint as a chance to make your brand feel unmistakably like itself."], ["03", "Measurable momentum", "A good idea is a beginning. We build the systems that let it compound." ]];

export default function About() {
  return <PageShell><main><PageIntro eyebrow="The studio" title={<>A little more <span className="italic text-[#ffbf00]">light</span> on the way in.</>} description="Luminor is an independent social and digital studio for brands with ambition, taste, and somewhere meaningful to go next." />
    <section className="mx-auto grid max-w-[1320px] gap-12 px-5 pb-24 lg:grid-cols-[0.85fr_1.15fr] lg:px-8 lg:pb-32" data-testid="about-story-section"><div className="rounded-3xl bg-[#1a1814] p-8 text-[#fffbf2] sm:p-12"><Globe2 className="size-9 text-[#ffbf00]" /><p className="mt-20 font-serif text-4xl leading-tight sm:text-5xl" data-testid="about-story-quote">We illuminate the good stuff that already exists inside your brand.</p></div><div className="flex flex-col justify-center"><Eyebrow>Our point of view</Eyebrow><h2 className="mt-5 font-serif text-4xl tracking-tight sm:text-5xl" data-testid="about-story-title">The feed is crowded. Your thinking shouldn’t be.</h2><p className="mt-6 text-lg leading-8 text-[#575247]">We started Luminor because the brands we admired were being asked to choose between creative that felt beautiful and creative that performed. We never believed in that trade-off.</p><p className="mt-5 text-lg leading-8 text-[#575247]">Today, our strategists, creators, and growth partners work as one small, sharp team — finding the signal, making it magnetic, and measuring what happens next.</p><Link to="/services" className="mt-8 inline-flex items-center text-sm font-semibold" data-testid="about-story-services-link">See how we work <ArrowRight className="ml-2 size-4" /></Link></div></section>
    <section className="border-y border-[#e8e1ce] bg-[#f7f1e3]" data-testid="about-values-section"><div className="mx-auto max-w-[1320px] px-5 py-20 lg:px-8 lg:py-28"><Eyebrow>What we believe</Eyebrow><div className="mt-10 grid gap-px overflow-hidden rounded-3xl border border-[#e8e1ce] bg-[#e8e1ce] md:grid-cols-3">{values.map(([number, title, text]) => <div key={number} className="bg-[#fffbf2] p-7 sm:p-9" data-testid={`about-value-${number}`}><span className="font-mono text-xs text-[#ffbf00]">{number}</span><h3 className="mt-16 font-serif text-3xl">{title}</h3><p className="mt-4 text-sm leading-6 text-[#575247]">{text}</p></div>)}</div></div></section>
    <section className="bg-[#1a1814] text-[#fffbf2]" data-testid="about-team-section"><div className="mx-auto max-w-[1320px] px-5 py-24 lg:px-8 lg:py-32"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><Eyebrow>People behind the light</Eyebrow><h2 className="mt-5 font-serif text-5xl tracking-tight">The team, in focus.</h2></div><p className="max-w-sm text-sm leading-6 text-[#b9b1a2]">Senior thinking, generous collaboration, and just enough healthy obsession.</p></div><div className="mt-12 grid gap-6 md:grid-cols-3">{team.map(([name, role, image]) => <div key={name} data-testid={`team-card-${name.toLowerCase().replaceAll(" ", "-")}`}><div className="aspect-[4/5] overflow-hidden rounded-3xl"><img src={image} alt={name} className="size-full object-cover grayscale transition duration-700 hover:scale-105 hover:grayscale-0" /></div><h3 className="mt-5 font-serif text-2xl">{name}</h3><p className="mt-1 text-sm text-[#b9b1a2]">{role}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-[1320px] px-5 py-24 lg:px-8 lg:py-32" data-testid="about-difference-section"><div className="grid gap-12 lg:grid-cols-2 lg:items-end"><div><Eyebrow>The difference</Eyebrow><h2 className="mt-5 max-w-xl font-serif text-5xl tracking-tight">More considered than an agency. More connected than a freelancer.</h2></div><div className="space-y-4 text-sm">{["One senior team from first thought to final report", "Strategy and creative in the same room", "A clear point of view, built around your actual numbers"].map((text) => <div key={text} className="flex items-center gap-3 border-b border-[#e8e1ce] pb-4" data-testid={`about-difference-${text.slice(0, 8).toLowerCase().replaceAll(" ", "-")}`}><Check className="size-4 text-[#ffbf00]" />{text}</div>)}</div></div></section>
    <section className="border-t border-[#e8e1ce] bg-[#f7f1e3]" data-testid="about-cta-section"><div className="mx-auto max-w-[1320px] px-5 py-20 lg:px-8"><Testimonial quote="The best partner is the one who makes your ambition feel more achievable." name="The Luminor philosophy" role="Since 2018" /></div></section>
  </main></PageShell>;
}